<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SmartPlayout.Contracts</AssemblyName>
    <RootNamespace>SmartPlayout.Contracts</RootNamespace>
  </PropertyGroup>
</Project>
