<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>SmartPlayout.CodecsFFM</AssemblyName>
    <RootNamespace>SmartPlayout.CodecsFFM</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen.Abstractions" Version="9.0.1.1" />
    <PackageReference Include="FFmpeg.AutoGen.Bindings.DynamicallyLoaded" Version="9.0.1.1" />
    <ProjectReference Include="..\SmartPlayout.FileFFM\SmartPlayout.FileFFM.csproj" />
  </ItemGroup>
</Project>
