const { contextBridge, ipcRenderer, webUtils } = require("electron");
contextBridge.exposeInMainWorld("playoutAPI", {
  pickMedia: () => ipcRenderer.invoke("pick-media"),
  resolveNetworkMedia: (url) =>
    ipcRenderer.invoke("resolve-network-media", url),
  savePlaylistFile: (items) => ipcRenderer.invoke("save-playlist-file", items),
  loadPlaylistFile: () => ipcRenderer.invoke("load-playlist-file"),
  saveProjectFile: (data) => ipcRenderer.invoke("save-project-file", data),
  loadProjectFile: () => ipcRenderer.invoke("load-project-file"),
  setAutoStart: (enabled) => ipcRenderer.invoke("set-auto-start", enabled),
  pickLogo: () => ipcRenderer.invoke("pick-logo"),
  pickFont: () => ipcRenderer.invoke("pick-font"),
  probeMedia: (file) => ipcRenderer.invoke("probe-media", file),
  openMediaFolder: (file) => ipcRenderer.invoke("open-media-folder", file),
  startRTMP: (cfg) => ipcRenderer.invoke("start-rtmp", cfg),
  stopRTMP: () => ipcRenderer.invoke("stop-rtmp"),
  startUDP: (cfg) => ipcRenderer.invoke("start-udp", cfg),
  stopUDP: () => ipcRenderer.invoke("stop-udp"),
  outputInfo: () => ipcRenderer.invoke("output-info"),
  networkInterfaces: () => ipcRenderer.invoke("network-interfaces"),
  readClipboardText: () => ipcRenderer.invoke("read-clipboard-text"),
  systemStats: () => ipcRenderer.invoke("system-stats"),
  droppedFilePath: (file) => webUtils.getPathForFile(file),
  probeDeckLink: () => ipcRenderer.invoke("probe-decklink"),
  startDeckLink: (cfg) => ipcRenderer.invoke("start-decklink", cfg),
  ffplayPreview: (file) => ipcRenderer.invoke("ffplay-preview", file),
  startCompatPreview: (cfg) => ipcRenderer.invoke("start-compat-preview", cfg),
  setEngineConfig: (cfg) => ipcRenderer.invoke("set-engine-config", cfg),
  detectCodecEngine: (cfg) => ipcRenderer.invoke("detect-codec-engine", cfg),
  stopPreview: () => ipcRenderer.invoke("stop-preview"),
  checkFFmpeg: () => ipcRenderer.invoke("check-ffmpeg"),
  installFFmpeg: () => ipcRenderer.invoke("install-full-ffmpeg"),
  installYtDlp: () => ipcRenderer.invoke("install-ytdlp"),
});
