<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>SmartPlayout.EncoderFFM</AssemblyName>
    <RootNamespace>SmartPlayout.EncoderFFM</RootNamespace>
  </PropertyGroup>
</Project>
